//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klassementen.
        /// </summary>
        internal static string Classifications {
            get {
                return ResourceManager.GetString("Classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hieronder kan je de rangschikking vinden per afdeling of provincie..
        /// </summary>
        internal static string ClassificationsSubTtitle {
            get {
                return ResourceManager.GetString("ClassificationsSubTtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord bevestigen.
        /// </summary>
        internal static string ConfirmPasswordLbl {
            get {
                return ResourceManager.GetString("ConfirmPasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord bevestigen*.
        /// </summary>
        internal static string ConfirmPasswordLblRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordLblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve je wachtwoord te bevestigen.
        /// </summary>
        internal static string ConfirmPasswordRequiredErrormessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredErrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres bestaat alreeds.
        /// </summary>
        internal static string EmailAddressAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        internal static string EmailaddressLbl {
            get {
                return ResourceManager.GetString("EmailaddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres*.
        /// </summary>
        internal static string EmailaddressLblRequired {
            get {
                return ResourceManager.GetString("EmailaddressLblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve je e-mailadres in te vullen.
        /// </summary>
        internal static string EmailaddressRequiredErrormessage {
            get {
                return ResourceManager.GetString("EmailaddressRequiredErrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        internal static string FirstnameLbl {
            get {
                return ResourceManager.GetString("FirstnameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam*.
        /// </summary>
        internal static string FirstnameLblRequired {
            get {
                return ResourceManager.GetString("FirstnameLblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve je voornaam in te vullen.
        /// </summary>
        internal static string FirstnameRequiredErrormessage {
            get {
                return ResourceManager.GetString("FirstnameRequiredErrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben jij voetbal minded en ben je graag op de hoogte over de stand van zaken van je favoriete ploeg? Dan ben je hier op de juiste plaats. Van nationaal tot provinciaal voetbal, over alle voetbalreeksen van Vlaanderen. Hier vind je alle uitslagen en klassementen van je favoriete club..
        /// </summary>
        internal static string HomeIntro {
            get {
                return ResourceManager.GetString("HomeIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string LastnameLbl {
            get {
                return ResourceManager.GetString("LastnameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam*.
        /// </summary>
        internal static string LastnameLblRequired {
            get {
                return ResourceManager.GetString("LastnameLblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve je naam in te vullen.
        /// </summary>
        internal static string LastnameRequiredErrormessage {
            get {
                return ResourceManager.GetString("LastnameRequiredErrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog geen account?.
        /// </summary>
        internal static string NotAnAccountYet {
            get {
                return ResourceManager.GetString("NotAnAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten?.
        /// </summary>
        internal static string PasswordForgotten {
            get {
                return ResourceManager.GetString("PasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        internal static string PasswordLbl {
            get {
                return ResourceManager.GetString("PasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord*.
        /// </summary>
        internal static string PasswordLblRequired {
            get {
                return ResourceManager.GetString("PasswordLblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve je wachtwoord in te vullen.
        /// </summary>
        internal static string PasswordRequiredErrormessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoorden komen niet overeen.
        /// </summary>
        internal static string PasswordsDoNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzenden.
        /// </summary>
        internal static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreer hier.
        /// </summary>
        internal static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
